version: '3'

services:
  node1: &node_base
    build:
      context: .
      dockerfile: ./node/Dockerfile
    container_name: node1
    ports:
      - "4001:4000"
      - "5001:5000"
      - "6001:6000"
    environment:
      - MASTER_HOST=master
      - MASTER_PORT=8000
      - NODE_GRPC_PORT=4000
      - NODE_UPLOAD_PORT=5000
      - NODE_DOWNLOAD_PORT=6000
    depends_on:
      - master
    # deploy:
    #   replicas: 5


  node2:
    <<: *node_base
    container_name: node2
    ports:
      - "4002:4000"
      - "5002:5000"
      - "6002:6000"

  node3:
    <<: *node_base
    container_name: node3
    ports:
      - "4003:4000"
      - "5003:5000"
      - "6003:6000"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    environment:
      - MASTER_HOST=master
      - MASTER_PORT=8000
      - NODE_UPLOAD_PORT=5000
      - NODE_DOWNLOAD_PORT=6000
    depends_on:
      - master

  master:
    build:
      context: .
      dockerfile: ./master/Dockerfile
    container_name: master
    ports:
      - "8000:8000"
    environment:
      - MASTER_PORT=8000
      - NODES_COUNT=3
      - NODES_HOSTS=node1,node2,node3
      - NODE_UPLOAD_PORT=5000
      - NODE_DOWNLOAD_PORT=6000

