// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: master_client.proto

package master_client

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientoMasterServiceClient is the client API for ClientoMasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientoMasterServiceClient interface {
}

type clientoMasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientoMasterServiceClient(cc grpc.ClientConnInterface) ClientoMasterServiceClient {
	return &clientoMasterServiceClient{cc}
}

// ClientoMasterServiceServer is the server API for ClientoMasterService service.
// All implementations must embed UnimplementedClientoMasterServiceServer
// for forward compatibility
type ClientoMasterServiceServer interface {
	mustEmbedUnimplementedClientoMasterServiceServer()
}

// UnimplementedClientoMasterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientoMasterServiceServer struct {
}

func (UnimplementedClientoMasterServiceServer) mustEmbedUnimplementedClientoMasterServiceServer() {}

// UnsafeClientoMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientoMasterServiceServer will
// result in compilation errors.
type UnsafeClientoMasterServiceServer interface {
	mustEmbedUnimplementedClientoMasterServiceServer()
}

func RegisterClientoMasterServiceServer(s grpc.ServiceRegistrar, srv ClientoMasterServiceServer) {
	s.RegisterService(&ClientoMasterService_ServiceDesc, srv)
}

// ClientoMasterService_ServiceDesc is the grpc.ServiceDesc for ClientoMasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientoMasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "master_client.ClientoMasterService",
	HandlerType: (*ClientoMasterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "master_client.proto",
}
